export const BASE_URL = 'https://oraclemanage.duckdns.org/studio-service';
export const ENDPOINTS = {
  LOGIN: '/users/login',
  REFRESH_TOKEN: '/password/refreshToken',
  RESET_PASSWORD: '/password/reset',
  VERIFY_OTP: '/password/verify',
  DASHBOARD: '/dashboard/getDashboardDetails',
  STUDENTS: '/students',
  CLIENTS: '/clients',
  INSTRUCTORS: '/instructors',
  ACTIVITIES: '/activities',
  BOOKINGS: '/booking',
  PAYMENTS: '/payments',
  EXPENSES: '/expenses',
  ENQUIRIES: '/enquiries',
  BRANCHES: '/branch',
  COMMUNICATION: '/communication',
  REPORTS: '/reports',
  TEMPLATES: '/genericTemplate',
  ATTENDANCE: '/attendance',
  STUDENT_ACTIVITIES: '/studentActivities',
  INSTRUCTOR_ACTIVITIES: '/instructorActivities',
  MEMBERSHIP_PACKAGES: '/membershipPackages',
  BULK_UPLOAD: '/bulkUpload',
};
