export const FEATURE_KEYS = {
  // for all
  CLIENT: "CLIENT",
  BOOKINGS: "BOOKINGS",
  INSTRUCTOR: "INSTRUCTOR",
  STUDENT: "STUDENT",

  // none
  WHATSAPP_SERVER: "WHATSAPP_SERVER",
  PAYMENT_DATE: "PAYMENT_DATE",
  BATCH: "BATCH",
  BULK_UPLOAD: "BULK_UPLOAD",

  // by user
  BRANCH: "BRANCH",
  ACTIVITY: "ACTIVITY",
  COMMUNICATION: "COMMUNICATION",
  PAYMENTS: "PAYMENTS",
  EXPENSE: "EXPENSE",
  ANALYSIS: "ANALYSIS",
  REPORTS: "REPORTS",
  ENQUIRY: "ENQUIRY",
  TEMPLATES: "TEMPLATES",
  MEMBERSHIP_PLAN_TABLE: "MEMBERSHIP_PLAN_TABLE",
};
